server:
  port: 7777


spring:
  profiles:
    active: local

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 90

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package:
    com.zhong.mall.tiny.mbg.model

jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer
